### ISSUE TITLE
Windows Defender treats app as a virus

### ISSUE THREAD

**Issue by VoiditeDev** [CloneTrooper1019/Rbx2Source#104]
**Describe the bug**
Windows Defender says that it's a virus

**To Reproduce**
1. Go to the app
2. See the Screen

**Expected behavior**
I expected it to open the app normally

**Screenshots**
![image](https://github.com/MaximumADHD/Rbx2Source/assets/142426954/94255a6b-e4e4-4dd2-a7f5-ad11a4f5a4e5)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Version 22H2

**Additional context**
I believe this isn't a virus yet it thinks that

**Comment by qfoxb** [comment]
this is because the app is unsigned and a code signing certificate is expensive.  Press more info then run anyway. Windows does this for all unsigned apps
Sent from my iPhone
