### ISSUE TITLE
User doesn't exist even if it does.

### ISSUE THREAD

**Issue by TheScunt** [CloneTrooper1019/Rbx2Source#11]
**This is annoying, im trying to export my roblox character but it says it doesn't exist, even if im not banned and my username is correct, can you fix this, please?** (Does not affect every roblox character, however, but the main and my alts are affected, and many others.)

![rbx](https://user-images.githubusercontent.com/39019954/39670191-1471e726-50b4-11e8-9a13-0a1f51eaccea.JPG)

**Comment by CloneTrooper1019** [comment]
I'll look into this.
They may have changed a web API or something.

**Comment by awesomeandyb** [comment]
I have the same problem.
It shows up for other characters but not me!

**Comment by CloneTrooper1019** [comment]
Apologies for the delay in fixing this, I've been super busy the past few months with my job and college.
I'm working on fixing it now.

**Comment by ilyescat888** [comment]
where is the bug being fixed

**Comment by CloneTrooper1019** [comment]
I was able to fix the issue, but I ran into another blocker which is going to take me a lot longer to fix.
Some of Roblox's avatar files are now using the binary file format, and my program doesn't know how to handle that yet.

**Comment by AlexSFM** [comment]
We Can Have An Older Version Of It??? Like 2.0.7. And I Sugest A Thing,To We Can Have Maps From Minigames In SourceFilmmaker,Tf2 And Others.

**Comment by CloneTrooper1019** [comment]
@AlexSFM The program is broken because it works off of live data from roblox.com, and because of changes to how Roblox is storing the data. Rolling back the program won't fix it.
I promise I will get this fixed soon, I just need to find some downtime to work on it.

**Comment by CloneTrooper1019** [comment]
Should be fixed now.
