### ISSUE TITLE
Rbx2source naked model

### ISSUE THREAD

**Issue by Dimanx64** [CloneTrooper1019/Rbx2Source#119]
ok so i tried to import my friend into garry's mod. and he dosent have pants. he got shorts. but for some reason! rbx2source didnt imported shorts, so my friend down is naked. his nickname: VFGGUJFJG
![Снимок экрана 2024-04-19 161049](https://github.com/MaximumADHD/Rbx2Source/assets/167023035/23c66850-54a4-49f2-acde-cc1f4f1bf2d3)

**Comment by qfoxb** [comment]
Is he wearing layered clothing

**Comment by Dimanx64** [comment]
> Is he wearing layered clothing

Probably

**Comment by qfoxb** [comment]
> > Is he wearing layered clothing
> 
> Probably

not supported by rbx2source

**Comment by Dimanx64** [comment]
> > > Is he wearing layered clothing
> > 
> > 
> > Probably
> 
> not supported by rbx2source

Im know for now
