### ISSUE TITLE
Cant assemble model for sfm

### ISSUE THREAD

**Issue by RunFake** [CloneTrooper1019/Rbx2Source#120]
I wanted to get the the avatar of a friend (Arda_hyz38) into sfm but the it couldnt assemble the model.
![image](https://github.com/MaximumADHD/Rbx2Source/assets/167470611/80703e09-f1f2-4b64-913f-33aecd96865e)
For my and another friends avatar Rbx2source worked by for this one it just does not do it.
Does anyone know why this happends

**Comment by BaconJesus8429** [comment]
Figured out the problem for ya, if you used an extension that changed the limit of accessorys like better roblox then it fails to compile the extra accessorys and crashes. Have your friend change their avatar a bit for you and it should work.

**Comment by Dimanx64** [comment]
Did your character got 3d clothes,dynamic heads, etc, It not supports it

**Comment by RunFake** [comment]
> Did your character got 3d clothes,dynamic heads, etc, It not supports it

yea i found that out pretty much instanly after making this issue just forgot to close the issue, thanks for replying

**Comment by Dimanx64** [comment]
pretty much tell your friend to remove this dynamic head
