### ISSUE TITLE
"FATAL ERROR: unable to find gameinfo.txt

### ISSUE THREAD

**Issue by alvaradodylan** [CloneTrooper1019/Rbx2Source#14]
i was compiling a character to garry's mod and then this error popped up

https://imgur.com/a/2quh8ry

i honestly have no idea what any of this means. can i get some help?

**Comment by ClusterTheChaosDude** [comment]
Same

**Comment by CloneTrooper1019** [comment]
This is a problem with garrys mod itself, not with my program.
You should still be able to insert the ragdoll in-game.

**Comment by ilyacvasha** [comment]
i have error: cannot find on your PC Steam, but i have it!
