### ISSUE TITLE
'value cannot be null'

### ISSUE THREAD

**Issue by CFoxxo** [CloneTrooper1019/Rbx2Source#16]
tried compiling old accounts to gather old outfit's models.

usernames tried:
LOSERGUY15
roungkiller555
cheergabi101

![image](https://user-images.githubusercontent.com/35355438/42121721-1cb4c98e-7c02-11e8-9dd5-be3fafc124aa.png)

**Comment by CloneTrooper1019** [comment]
Yeah I know.

Unfortunately some of Roblox's assets have been updated to use their binary file format, and my program doesn't know how to handle that at the moment. I do plan to address this though, its just going to take some time.
