### ISSUE TITLE
Unable to find gameinfo.txt + User Does Not Exist

### ISSUE THREAD

**Issue by nunziofumia** [CloneTrooper1019/Rbx2Source#18]
so, i tried porting my friend's robloxian into a gmod ragdoll, however whenever i compile the model, and press the view button, it says unable to find gameinfo.txt. i have steam open, and downloaded rbx2source's new version. idk what to do?

also, i'm trying to compile my robloxian, however it keeps saying user doesnt exist, this doesnt happen for my friends robloxians

**Comment by CloneTrooper1019** [comment]
Will take a look.

**Comment by nunziofumia** [comment]
great! please reply when you have the chance

**Comment by CloneTrooper1019** [comment]
Are you still getting the "User doesn't exist" error?

The `gameinfo.txt` issue is actually a quirk specific to Garry's Mod. I'll see if I can hack around it, but its more the fault of gmod than it is my program.

**Comment by nunziofumia** [comment]
i no longer get the User doesn't exist glitch, but i still get the gameinfo.txt error. i do have gmod and steam open, still no dice :P an image of the error is below
![capture](https://user-images.githubusercontent.com/42390727/44472179-a3e70200-a5fb-11e8-9f14-c71850f22640.PNG)

**Comment by Thehelper104** [comment]
Still happens.

**Comment by CloneTrooper1019** [comment]
I have a fix coming up for this soon, patience is a virtue :)

**Comment by Thehelper104** [comment]
good! also make sure you add the new 2017 roblox icon soon!  👍

**Comment by Thehelper104** [comment]
![image](https://user-images.githubusercontent.com/38369997/44557962-1ee90f00-a707-11e8-9b61-7a724a74aa8b.png) how about this?

**Comment by CloneTrooper1019** [comment]
I'll take care of it myself. I appreciate it though.

**Comment by CloneTrooper1019** [comment]
Just released a patch. Let me know if the `gameinfo.txt` issue is still happening.

**Comment by nunziofumia** [comment]
checked, and the gameinfo.txt issue isn't happening anymore! thx clone
