### ISSUE TITLE
Unable to find gameinfo.txt

### ISSUE THREAD

**Issue by TechnologicalLucas** [CloneTrooper1019/Rbx2Source#21]
Even if i have that file in garry's mod file what i gotta do? I don't get any errors except that one. Is there a way to fix it?
![image](https://user-images.githubusercontent.com/33066962/44553871-55be2580-a705-11e8-98c8-a325b63c15b8.png)

Is there anything here to modify?
![image](https://user-images.githubusercontent.com/33066962/44553904-725a5d80-a705-11e8-966b-151dbd9345a4.png)

**Comment by CloneTrooper1019** [comment]
Duplicate of https://github.com/CloneTrooper1019/Rbx2Source/issues/18
