### ISSUE TITLE
Failed to assemble model: (400) Bad Request (Error appeared multiple times)

### ISSUE THREAD

**Issue by awesomeandyb** [CloneTrooper1019/Rbx2Source#25]
I don't know why this happens, but it DOES.... I tried compiling my model, but it didn't work.
Here is a screen shot:
![error message on rbx2source](https://user-images.githubusercontent.com/33814766/44757694-03f71000-aaf6-11e8-87d3-2c8bcf4f0f72.PNG)

**Comment by Thehelper104** [comment]
Its gone. i have a patch for it.

**Comment by Thehelper104** [comment]
i will.

**Comment by Thehelper104** [comment]
just wait for the.zip

**Comment by Thehelper104** [comment]
Also this is able to load up deleted roblox people!

**Comment by Thehelper104** [comment]
https://drive.google.com/open?id=1WYx8q2kvaejRAXsTsZdftWwC3HbcRTyI you will have to click NEW_Rbx2Source.exe so it can work.

**Comment by awesomeandyb** [comment]
Awesome, thanks!

**Comment by realCraymotherlol** [comment]
Nope its fixed on the new version you can close this now.

**Comment by ADuckInBlack** [comment]
jeez, this has been here a while
