### ISSUE TITLE
Should you just use my fixed version  Clonetrooper? 

### ISSUE THREAD

**Issue by Thehelper104** [CloneTrooper1019/Rbx2Source#28]
https://drive.google.com/open?id=1WYx8q2kvaejRAXsTsZdftWwC3HbcRTyI replace the one one with this. use NEW_RBX2SOURCE.EXE as the download link

**Comment by CloneTrooper1019** [comment]
I already fixed the bug that was breaking the program previously. You don’t know what you’re doing.
