### ISSUE TITLE
Failed to assemble model (gear/accessories)

### ISSUE THREAD

**Issue by medicnod** [CloneTrooper1019/Rbx2Source#31]
![error](https://user-images.githubusercontent.com/46442759/50762313-ed38a500-12af-11e9-9e65-2d99d48aa273.PNG)
![error2](https://user-images.githubusercontent.com/46442759/50762377-19ecbc80-12b0-11e9-8aad-ae02288e6db4.PNG)
https://www.roblox.com/catalog/63241364/Darkseed-The-Pendant when i compile this accessories, i have a error like first picture. why this happen?

Im not good at English. im sorry :(

**Comment by CloneTrooper1019** [comment]
Thanks for the report. This is probably another localization problem with visual studio.
I will try to have a fix out for this soon. For now, it should work if you set your system language to English.

**Comment by CloneTrooper1019** [comment]
Heyo, I just released an update that should address this issue
Is it still happening for you?

**Comment by medicnod** [comment]
![Capture](https://user-images.githubusercontent.com/46442759/56087937-af4fac00-5eb0-11e9-8aef-76e41213d908.PNG)
![Capture1](https://user-images.githubusercontent.com/46442759/56087939-b080d900-5eb0-11e9-8666-9d43e79088c1.PNG)

**Comment by AKG51** [comment]
This has been happening now

**Comment by AKG51** [comment]
This has been happening 
https://photos.app.goo.gl/bLVqZx6yRaceUZXJA
What do i do

**Comment by CloneTrooper1019** [comment]
This is fixed now.
