### ISSUE TITLE
Invalid AssetId and Texture Compiling Issue

### ISSUE THREAD

**Issue by realCraymotherlol** [CloneTrooper1019/Rbx2Source#33]
It doesn't want to cache id's when trying to compile the model as well.
![image](https://user-images.githubusercontent.com/42814427/52584721-1c07e500-2e33-11e9-9769-66aeb992029c.png)

it sometimes also fails to compile texture's making them look green. 
![image](https://user-images.githubusercontent.com/42814427/52584927-b10ade00-2e33-11e9-91ad-43815b9c841d.png)

**Comment by DerpzDeNugget** [comment]
I've had both happen to me.
One with the invalid assetId when starting the program
And one with my conversion of my banned alt

**Comment by CloneTrooper1019** [comment]
Heyo, I just released an update that should address this issue
Is it still happening for you?
