### ISSUE TITLE
"Roundy" Head not working || Input string was not in a correct format.

### ISSUE THREAD

**Issue by DerpzDeNugget** [CloneTrooper1019/Rbx2Source#37]
The "Roundy" Face on Roblox fails to work and pops up with the error "Input string was not in a correct format." Any way to fix this? Heres a screenshot of the error:
![image](https://user-images.githubusercontent.com/39784890/57589002-4a21c180-7515-11e9-9c01-e119d707a7be.png)
Thank you, And please tell me when the fix is going to be applied.
Best regards, Derpz

PS: I mean for the avatar section. If the avatar selected uses it, It fails to compile.

**Comment by CloneTrooper1019** [comment]
Can you send me a link to this item?

**Comment by TheTrueCubic** [comment]
This still needs to be fixed. I also have this problem. By the way, here's the link: https://www.roblox.com/catalog/6340213/Roundy

**Comment by CloneTrooper1019** [comment]
After digging into this a little further, it looks like Roblox unintentionally fixed this problem for me with a recent change they made to the old mesh heads. I'm gonna consider this fixed and close the issue. Let me know if you find any evidence contrary.
