### ISSUE TITLE
This program no longer works.

### ISSUE THREAD

**Issue by theservermainer** [CloneTrooper1019/Rbx2Source#39]
![error](https://user-images.githubusercontent.com/18509793/59567483-6812a280-903c-11e9-932b-667a3b13c5bd.PNG)
Everytime i try to enter an existing username, it will spit out this error, making this unusable.
The accessories wont work either.

**Comment by CloneTrooper1019** [comment]
Just made an update to the program. Let me know if you're still seeing these errors.

**Comment by theservermainer** [comment]
I am still seeing them. I had to download it twice to make sure.

**Comment by CloneTrooper1019** [comment]
That’s odd. You might have some corrupted data.
I would advise manually clearing the program’s save data and installing it fresh again:

1. Close Rbx2Source if you have it running.
2. Open the Windows registry editor (regedit.exe)
3. Navigate to HKEY_CURRENT_USER\Software
4. Delete the key named Rbx2Source, and close regedit.
5. Go into your file browser and type %localappdata% into the path (where it says C:\...)
6. Delete the folder named Rbx2Source

Doing the above will clear all of the program’s saved data.
From there, try running Rbx2Source again, and see if any of the issues persist.

If you have any trouble with the instructions above, let me know. Apologies for the issues!

**Comment by theservermainer** [comment]
Fixed! Thank you for the guide!
