### ISSUE TITLE
Compiles Don't Show on Garry's Mod

### ISSUE THREAD

**Issue by TyrannoWright** [CloneTrooper1019/Rbx2Source#40]
Found an odd issue with Garry's Mod no longer reading the program's compiled models. I have tried the manual "addons" trick, but it still did not appear in the spawn menu either. Instead, I had to compile it for a different Source game (HL2, in this case) and check from there. It works, but why it doesn't show for Garry's Mod assets or addons confuses me.

**Comment by CloneTrooper1019** [comment]
This is probably an issue on their end and not mine. I'd rather not hack around their issues.
