### ISSUE TITLE
FATAL ERROR "Cannot find Steam on this PC! Try running Steam so Rbx2Source can detect it."

### ISSUE THREAD

**Issue by freddy1232426** [CloneTrooper1019/Rbx2Source#48]
This happens to me all the time when I want to port ROBLOX models to SFM and I have Steam open as administrator and without administrator I also run RBX2Source as administrator, add Rbx2Source as a non-Steam game and it doesn't work. https://gyazo.com/bdf6dd63398dc60b0ed438db781be390

**Comment by CloneTrooper1019** [comment]
Let me know if this is still occurring with v2.60
https://github.com/CloneTrooper1019/Rbx2Source/commit/d6b73d4495d7bf596a5a94f472eb102c1bf3b43a
