### ISSUE TITLE
Textures are not right

### ISSUE THREAD

**Issue by Zyle45** [CloneTrooper1019/Rbx2Source#49]
![2020-07-26 (1)](https://user-images.githubusercontent.com/68819444/88484239-7f140b80-cf43-11ea-8f8a-b6d05bfde585.png)

the textures on the pal hair appear greenish instead of the normal brown look.

**Comment by CloneTrooper1019** [comment]
The reason this is happening is interesting. Roblox set the VertexColor of the pal hair to `1.2, 1.2, 1.4` which is an out of range value I was not expecting. I think I can fix this if I just forcefully clamp the values back into the [0-1] range.

**Comment by CloneTrooper1019** [comment]
Fixed this issue.
https://github.com/CloneTrooper1019/Rbx2Source/commit/be052af865d7f3d5e994e587c475df52d3511886
