### ISSUE TITLE
"Blockhead" head for avatar can't assemble

### ISSUE THREAD

**Issue by OldmanEstimanJr** [CloneTrooper1019/Rbx2Source#50]
![issue](https://user-images.githubusercontent.com/69188274/89264217-23ddc980-d665-11ea-8709-e8780c18afc0.png)
I had the same issue with DerpzDeNugget. Everything will generate but it stops at generating the head part. Just wanted to know if this was fixed for the Roundy head and not for the Blockhead. Either way, I'd like a fix for both of them. Thanks
Blockhead: [https://www.roblox.com/catalog/6340101/Blockhead](url)
My profile: [https://www.roblox.com/users/137692444/profile](url)

**Comment by CloneTrooper1019** [comment]
I just released an update that might have fixed this.
Are you still seeing it happen?

**Comment by CloneTrooper1019** [comment]
After digging into this a little further, it looks like Roblox unintentionally fixed this problem for me with a recent change they made to the old mesh heads. I'm gonna consider this fixed and close the issue. Let me know if you find any evidence contrary.

**Comment by OldmanEstimanJr** [comment]
Ah thanks man.It works fine now. Appreciated! Anyways here have my Roblox
character in gm_construct
[image: robloxavatargmail.png]

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
