### ISSUE TITLE
"Index and count must refer to a location within the buffer. Parameter name: bytes"

### ISSUE THREAD

**Issue by B1ackydecatty** [CloneTrooper1019/Rbx2Source#51]
![image](https://user-images.githubusercontent.com/45589944/93664519-1dcf6b00-faa2-11ea-860c-2055eaf35f19.png)
i have used this before and it works just fine
and now its broken??? i don't know why.
also, the version is v2.52

**Comment by B1ackydecatty** [comment]
P.S. it happens to every avatar/user that i try to compile.

**Comment by zzakko69** [comment]
same happening with me

**Comment by CloneTrooper1019** [comment]
Working on this right now.

**Comment by CloneTrooper1019** [comment]
Should be fixed with https://github.com/CloneTrooper1019/Rbx2Source/commit/d6b73d4495d7bf596a5a94f472eb102c1bf3b43a
