### ISSUE TITLE
Some UGC hats textures will break.

### ISSUE THREAD

**Issue by B1ackydecatty** [CloneTrooper1019/Rbx2Source#52]
![image](https://user-images.githubusercontent.com/45589944/93708651-900b8280-fb6a-11ea-974b-cc82a2fb4dd0.png)
example like this, it happens to hats that have outlines and stuff.

**Comment by B1ackydecatty** [comment]
I found it out after trying to compile an user with this ugc hat. the textures weren't normal as i have seen this hat in normal form before.

**Comment by CloneTrooper1019** [comment]
I think I know why this is happening now and I'll get it fixed.
Roblox's LOD meshes got mixed into the data when I was updating the mesh format.

**Comment by CloneTrooper1019** [comment]
Fixed with v2.61
