### ISSUE TITLE
Question: Are you planning to add importing things from roblox studio?

### ISSUE THREAD

**Issue by B1ackydecatty** [CloneTrooper1019/Rbx2Source#53]
i will love to see it but at the same time, its gonna be really diffcult/hard to make this.
Hopefully though, good luck clone on your future updates.

**Comment by CloneTrooper1019** [comment]
I might make it possible to import HumanoidDescriptions at some point.

**Comment by B1ackydecatty** [comment]
Cool, i will look foward to it
