### ISSUE TITLE
Some avatars don't have some asset loaded 

### ISSUE THREAD

**Issue by B1ackydecatty** [CloneTrooper1019/Rbx2Source#54]
ORIGINAL LOOK:
![image](https://user-images.githubusercontent.com/45589944/93893279-0998a180-fd20-11ea-9d61-3d054a9249ab.png)
THE ONE THAT LOADED:
![image](https://user-images.githubusercontent.com/45589944/93893339-1917ea80-fd20-11ea-9055-273936d78f38.png)
this is just weird, i don't know why some assets won't load. it makes thing quite odd and somewhat nsfw.

**Comment by B1ackydecatty** [comment]
turns out, this happens to content deleted assets.

**Comment by CloneTrooper1019** [comment]
Would you say this issue is solved then?

**Comment by B1ackydecatty** [comment]
well not exactly but sorta i guess, its just that it can't load content deleted assets and i don't think there's any ways to fix it.
