### ISSUE TITLE
RBX2SOURCE can't build last geometry or smth, breaks and failed to make model

### ISSUE THREAD

**Issue by B1ackydecatty** [CloneTrooper1019/Rbx2Source#56]
![image](https://user-images.githubusercontent.com/45589944/100720222-a2226080-33f8-11eb-8d2b-bfd23a581584.png)
yes some reason this started happening recently
no clue where the error came from nor its source of problem

**Comment by B1ackydecatty** [comment]
have dm'd clone on twitter for this.

**Comment by CloneTrooper1019** [comment]
Fixed.
