### ISSUE TITLE
ERROR Model

### ISSUE THREAD

**Issue by RetroCode72** [CloneTrooper1019/Rbx2Source#6]
Hello CloneTrooper1019. I Have Recently Got An Issue With This Program: When I Compile An Avatar For Source Filmmaker, The Model Is Just An Error. Is There Any Way To Fix It? 

Thanks For Reading

Here´s A Screenshot Of The Error: 

![error](https://user-images.githubusercontent.com/20257737/33517863-de33137a-d78b-11e7-9523-2f1e1150db8b.png)

**Comment by KenIam** [comment]
How to fix the error software thingy? I still get it.
When I also try to view compiled model for Garry's Mod then it gives the error to find the gameinfo.txt thingy, though i have it.

**Comment by ARTGamingTV** [comment]
hello, I have ran into a problem where i'm trying to compile my roblox avatar and i type in my name with no mistakes and it says "This user does not exist" i'm wondering how to fix this problem so i can make my thumbnail for youtube. thanks, ART.
![capture](https://user-images.githubusercontent.com/40185856/41261737-b8d1e158-6da2-11e8-9f29-9af17e292e8f.PNG)

**Comment by SpiffyFlybro** [comment]
> hello, I have run into a problem where i'm trying to compile my roblox avatar and i type in my name with no mistakes and it says "This user does not exist" i'm wondering how to fix this problem so i can make my thumbnail for youtube. thanks, ART.
> ![capture](https://user-images.githubusercontent.com/40185856/41261737-b8d1e158-6da2-11e8-9f29-9af17e292e8f.PNG)

I have this issue too.

**Comment by Vukcanister** [comment]
Does anyone know the fix?
