### ISSUE TITLE
new error when compling avatars again.

### ISSUE THREAD

**Issue by B1ackydecatty** [CloneTrooper1019/Rbx2Source#63]
![image](https://user-images.githubusercontent.com/45589944/105674292-37863080-5f22-11eb-9c73-cd4dad6ad449.png)
not that i know of the source of the error 
version 2.61

**Comment by B1ackydecatty** [comment]
am not sure, it might be only happening to avatars with R15.

**Comment by B1ackydecatty** [comment]
nvm, its definitely something with the height of the avatar idk.

**Comment by B1ackydecatty** [comment]
or even maybe, certain accessory breaking it.

**Comment by CloneTrooper1019** [comment]
most likely the case.
I’ll investigate.

**Comment by B1ackydecatty** [comment]
i have a question rq, do you consider adding choosing avatar type for the avatar you are compiling?

**Comment by Xperia12** [comment]
Hey I also have that error, I don't know how to fix it :(

**Comment by B1ackydecatty** [comment]
The error doesnt happen again, so i am not sure if i could close or not
