### ISSUE TITLE
Rip off

### ISSUE THREAD

**Issue by fatsjnsdn** [CloneTrooper1019/Rbx2Source#7]
I'm ripped off. I tried to compile my avatar and it was R15 and when it was done, on Gmod it looked trashy and the stupid texture didn't work. Fix this now you jerk

**Comment by CloneTrooper1019** [comment]
‪A rip off when the program was free and open sourced.‬ ‪Right... that makes sense.‬
I will get to fixing this soon, for now I would advise you to learn some manners.

**Comment by fatsjnsdn** [comment]
ok sorry. It was using the Roblox 2.0 mesh
