### ISSUE TITLE
Textures render incorrectly

### ISSUE THREAD

**Issue by IsaiahTSE** [CloneTrooper1019/Rbx2Source#8]
I'm having an issue where the textures of my Roblox avatar didn't compile properly when I compiled it. It did successfully compile, but when I looked at it in Garry's Mod, the textures didn't look right. The hat and hair loaded correctly, but the actual character is just black with a brown thick line on it. It was an R15 avatar with Robloxian 2.0 package. Same thing happened compiling user MachRider94. The only successful compiles were Awesomelkeyou and Vuk_Time. Can you fix this?

**Comment by CloneTrooper1019** [comment]
I'm aware of this issue. Going to be looking into it soon.

**Comment by IsaiahTSE** [comment]
Ok, thanks.

**Comment by CloneTrooper1019** [comment]
Should be fixed in the newest patch.
Thank you for your patience. Let me know if there are any other issues!
https://github.com/CloneTrooper1019/Rbx2Source/commit/6b2bc9e56f70518d2ed2cfad67880bbbd3cb4c98
